using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using SecondBrain.Core.Interfaces;

namespace SecondBrain.Core.Entities;

[Table("chat_conversations")]
public class ChatConversation : ISoftDeletable
{
    [Key]
    [Column("id")]
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// UUIDv7 identifier for improved index performance (PostgreSQL 18).
    /// Generated by database default if not set.
    /// </summary>
    [Column("uuid_v7")]
    public Guid? UuidV7 { get; set; }

    [Column("title")]
    [MaxLength(500)]
    public string Title { get; set; } = string.Empty;

    [Column("provider")]
    [MaxLength(50)]
    public string Provider { get; set; } = string.Empty;

    [Column("model")]
    [MaxLength(100)]
    public string Model { get; set; } = string.Empty;

    [Column("rag_enabled")]
    public bool RagEnabled { get; set; } = false;

    [Column("agent_enabled")]
    public bool AgentEnabled { get; set; } = false;

    [Column("agent_rag_enabled")]
    public bool AgentRagEnabled { get; set; } = false;

    [Column("image_generation_enabled")]
    public bool ImageGenerationEnabled { get; set; } = false;

    [Column("agent_capabilities")]
    public string? AgentCapabilities { get; set; }

    [Column("vector_store_provider")]
    [MaxLength(50)]
    public string? VectorStoreProvider { get; set; }

    [Column("user_id")]
    [MaxLength(128)]
    public string UserId { get; set; } = string.Empty;

    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [Column("updated_at")]
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    // Soft delete properties
    [Column("is_deleted")]
    public bool IsDeleted { get; set; } = false;

    [Column("deleted_at")]
    public DateTime? DeletedAt { get; set; }

    [Column("deleted_by")]
    [MaxLength(128)]
    public string? DeletedBy { get; set; }

    // Navigation property for messages (stored in separate table)
    public List<ChatMessage> Messages { get; set; } = new();
}

[Table("chat_messages")]
public class ChatMessage
{
    [Key]
    [Column("id")]
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// UUIDv7 identifier for improved index performance (PostgreSQL 18).
    /// Generated by database default if not set.
    /// </summary>
    [Column("uuid_v7")]
    public Guid? UuidV7 { get; set; }

    [Column("conversation_id")]
    [MaxLength(128)]
    public string ConversationId { get; set; } = string.Empty;

    [Column("role")]
    [MaxLength(20)]
    public string Role { get; set; } = string.Empty; // "user" or "assistant"

    [Column("content")]
    public string Content { get; set; } = string.Empty;

    [Column("timestamp")]
    public DateTime Timestamp { get; set; } = DateTime.UtcNow;

    [Column("input_tokens")]
    public int? InputTokens { get; set; }

    [Column("output_tokens")]
    public int? OutputTokens { get; set; }

    [Column("duration_ms")]
    public double? DurationMs { get; set; }

    /// <summary>
    /// Whether token counts are actual provider values (true) or estimates (false)
    /// </summary>
    [Column("tokens_actual")]
    public bool? TokensActual { get; set; }

    /// <summary>
    /// Tokens used for reasoning/thinking (Claude, Gemini thinking modes)
    /// </summary>
    [Column("reasoning_tokens")]
    public int? ReasoningTokens { get; set; }

    /// <summary>
    /// Tokens used to create prompt cache (Claude)
    /// </summary>
    [Column("cache_creation_tokens")]
    public int? CacheCreationTokens { get; set; }

    /// <summary>
    /// Tokens read from prompt cache (Claude)
    /// </summary>
    [Column("cache_read_tokens")]
    public int? CacheReadTokens { get; set; }

    /// <summary>
    /// Tokens used by RAG context
    /// </summary>
    [Column("rag_context_tokens")]
    public int? RagContextTokens { get; set; }

    /// <summary>
    /// Number of RAG chunks included
    /// </summary>
    [Column("rag_chunks_count")]
    public int? RagChunksCount { get; set; }

    /// <summary>
    /// Tokens used for tool definitions (agent mode)
    /// </summary>
    [Column("tool_definition_tokens")]
    public int? ToolDefinitionTokens { get; set; }

    /// <summary>
    /// Tokens used for tool arguments (agent mode)
    /// </summary>
    [Column("tool_argument_tokens")]
    public int? ToolArgumentTokens { get; set; }

    /// <summary>
    /// Tokens used for tool results (agent mode)
    /// </summary>
    [Column("tool_result_tokens")]
    public int? ToolResultTokens { get; set; }

    /// <summary>
    /// RAG query log ID for feedback association (only for assistant messages with RAG)
    /// </summary>
    [Column("rag_log_id")]
    [MaxLength(128)]
    public string? RagLogId { get; set; }

    /// <summary>
    /// User feedback on RAG response quality ('thumbs_up' or 'thumbs_down')
    /// </summary>
    [Column("rag_feedback")]
    [MaxLength(20)]
    public string? RagFeedback { get; set; }

    /// <summary>
    /// Markdown renderer used to display this message ('custom' or 'llm-ui')
    /// </summary>
    [Column("markdown_renderer")]
    [MaxLength(20)]
    public string? MarkdownRenderer { get; set; }

    // Navigation property back to conversation (ignored to prevent circular serialization)
    [ForeignKey("ConversationId")]
    [JsonIgnore]
    public ChatConversation? Conversation { get; set; }

    // Navigation properties for related data
    public List<RetrievedNote> RetrievedNotes { get; set; } = new();
    public List<ToolCall> ToolCalls { get; set; } = new();
    public List<MessageImage> Images { get; set; } = new();
    public List<GeneratedImageData> GeneratedImages { get; set; } = new();
    public List<ThinkingStep> ThinkingSteps { get; set; } = new();
}

[Table("message_images")]
public class MessageImage
{
    [Key]
    [Column("id")]
    public string Id { get; set; } = string.Empty;

    [Column("message_id")]
    [MaxLength(128)]
    public string MessageId { get; set; } = string.Empty;

    [Column("base64_data")]
    public string Base64Data { get; set; } = string.Empty;

    [Column("media_type")]
    [MaxLength(100)]
    public string MediaType { get; set; } = string.Empty;

    [Column("file_name")]
    [MaxLength(255)]
    public string? FileName { get; set; }

    // Navigation property back to message (ignored to prevent circular serialization)
    [ForeignKey("MessageId")]
    [JsonIgnore]
    public ChatMessage? Message { get; set; }
}

[Table("tool_calls")]
public class ToolCall
{
    [Key]
    [Column("id")]
    public string Id { get; set; } = string.Empty;

    [Column("message_id")]
    [MaxLength(128)]
    public string MessageId { get; set; } = string.Empty;

    [Column("tool_name")]
    [MaxLength(100)]
    public string ToolName { get; set; } = string.Empty;

    [Column("arguments")]
    public string Arguments { get; set; } = string.Empty;

    [Column("result")]
    public string Result { get; set; } = string.Empty;

    [Column("executed_at")]
    public DateTime ExecutedAt { get; set; } = DateTime.UtcNow;

    [Column("success")]
    public bool Success { get; set; } = true;

    /// <summary>
    /// Text content that was streamed before this tool was invoked.
    /// Used to reconstruct the chronological order of text and tool calls in the UI.
    /// </summary>
    [Column("pre_tool_text")]
    public string? PreToolText { get; set; }

    // Navigation property back to message (ignored to prevent circular serialization)
    [ForeignKey("MessageId")]
    [JsonIgnore]
    public ChatMessage? Message { get; set; }
}

[Table("retrieved_notes")]
public class RetrievedNote
{
    [Key]
    [Column("id")]
    public string Id { get; set; } = string.Empty;

    [Column("message_id")]
    [MaxLength(128)]
    public string MessageId { get; set; } = string.Empty;

    [Column("note_id")]
    [MaxLength(128)]
    public string NoteId { get; set; } = string.Empty;

    [Column("title")]
    [MaxLength(500)]
    public string Title { get; set; } = string.Empty;

    [Column("tags", TypeName = "text[]")]
    public List<string> Tags { get; set; } = new();

    [Column("relevance_score")]
    public float RelevanceScore { get; set; }

    [Column("chunk_content")]
    public string ChunkContent { get; set; } = string.Empty;

    [Column("chunk_index")]
    public int ChunkIndex { get; set; }

    // Navigation property back to message (ignored to prevent circular serialization)
    [ForeignKey("MessageId")]
    [JsonIgnore]
    public ChatMessage? Message { get; set; }
}

[Table("generated_images")]
public class GeneratedImageData
{
    [Key]
    [Column("id")]
    public string Id { get; set; } = string.Empty;

    [Column("message_id")]
    [MaxLength(128)]
    public string MessageId { get; set; } = string.Empty;

    [Column("base64_data")]
    public string? Base64Data { get; set; }

    [Column("url")]
    [MaxLength(2048)]
    public string? Url { get; set; }

    [Column("revised_prompt")]
    public string? RevisedPrompt { get; set; }

    [Column("media_type")]
    [MaxLength(100)]
    public string MediaType { get; set; } = "image/png";

    [Column("width")]
    public int? Width { get; set; }

    [Column("height")]
    public int? Height { get; set; }

    // Navigation property back to message (ignored to prevent circular serialization)
    [ForeignKey("MessageId")]
    [JsonIgnore]
    public ChatMessage? Message { get; set; }
}

/// <summary>
/// Represents a single thinking/reasoning step during AI agent execution.
/// Stored with individual timestamps to preserve chronological display order.
/// </summary>
[Table("thinking_steps")]
public class ThinkingStep
{
    [Key]
    [Column("id")]
    public string Id { get; set; } = string.Empty;

    [Column("message_id")]
    [MaxLength(128)]
    public string MessageId { get; set; } = string.Empty;

    /// <summary>
    /// Order of this thinking step within the message (0-indexed)
    /// </summary>
    [Column("step_number")]
    public int StepNumber { get; set; }

    /// <summary>
    /// The thinking/reasoning content
    /// </summary>
    [Column("content")]
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// When this thinking step began (from streaming)
    /// </summary>
    [Column("started_at")]
    public DateTime StartedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// When this thinking step completed (null if still streaming)
    /// </summary>
    [Column("completed_at")]
    public DateTime? CompletedAt { get; set; }

    /// <summary>
    /// Duration in milliseconds (if available)
    /// </summary>
    [Column("duration_ms")]
    public double? DurationMs { get; set; }

    /// <summary>
    /// AI provider that generated this thinking (claude, grok, gemini, ollama, etc.)
    /// </summary>
    [Column("model_source")]
    [MaxLength(50)]
    public string? ModelSource { get; set; }

    // Navigation property back to message (ignored to prevent circular serialization)
    [ForeignKey("MessageId")]
    [JsonIgnore]
    public ChatMessage? Message { get; set; }
}
