using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using SecondBrain.Core.Interfaces;

namespace SecondBrain.Core.Entities;

/// <summary>
/// Indicates the format of note content.
/// </summary>
public enum ContentFormat
{
    /// <summary>Plain markdown content (legacy format)</summary>
    Markdown = 0,

    /// <summary>HTML content</summary>
    Html = 1,

    /// <summary>TipTap/ProseMirror JSON (canonical format for UI editing)</summary>
    TipTapJson = 2
}

[Table("notes")]
public class Note : ISoftDeletable
{
    [Key]
    [Column("id")]
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// UUIDv7 identifier for improved index performance (PostgreSQL 18).
    /// Generated by database default if not set.
    /// </summary>
    [Column("uuid_v7")]
    public Guid? UuidV7 { get; set; }

    [Column("title")]
    [MaxLength(500)]
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Text content of the note (markdown format for search and display).
    /// This is the primary content field used for full-text search and RAG.
    /// </summary>
    [Column("content")]
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// TipTap/ProseMirror JSON representation of the note content.
    /// This is the canonical format for UI editing - provides consistent
    /// formatting and eliminates lossy conversions between formats.
    /// When this field is present, it should be preferred for editing.
    /// </summary>
    [Column("content_json", TypeName = "jsonb")]
    public string? ContentJson { get; set; }

    /// <summary>
    /// Indicates the format of the Content field.
    /// Used for migration tracking and backward compatibility.
    /// </summary>
    [Column("content_format")]
    public ContentFormat ContentFormat { get; set; } = ContentFormat.Markdown;

    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [Column("updated_at")]
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    [Column("tags", TypeName = "text[]")]
    public List<string> Tags { get; set; } = new();

    [Column("is_archived")]
    public bool IsArchived { get; set; }

    [Column("user_id")]
    [MaxLength(128)]
    public string UserId { get; set; } = string.Empty;

    [Column("source")]
    [MaxLength(50)]
    public string Source { get; set; } = "web";

    [Column("external_id")]
    [MaxLength(256)]
    public string? ExternalId { get; set; }

    [Column("folder")]
    [MaxLength(256)]
    public string? Folder { get; set; }

    /// <summary>
    /// AI-generated summary of the note (considering title, tags, and content).
    /// Used for list views to avoid fetching full content.
    /// </summary>
    [Column("summary")]
    [MaxLength(1000)]
    public string? Summary { get; set; }

    // Soft delete properties
    [Column("is_deleted")]
    public bool IsDeleted { get; set; } = false;

    [Column("deleted_at")]
    public DateTime? DeletedAt { get; set; }

    [Column("deleted_by")]
    [MaxLength(128)]
    public string? DeletedBy { get; set; }

    /// <summary>
    /// Images attached to this note for multi-modal RAG support.
    /// </summary>
    public List<NoteImage> Images { get; set; } = new();
}
