using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using SecondBrain.Core.Interfaces;

namespace SecondBrain.Core.Entities;

[Table("notes")]
public class Note : ISoftDeletable
{
    [Key]
    [Column("id")]
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// UUIDv7 identifier for improved index performance (PostgreSQL 18).
    /// Generated by database default if not set.
    /// </summary>
    [Column("uuid_v7")]
    public Guid? UuidV7 { get; set; }

    [Column("title")]
    [MaxLength(500)]
    public string Title { get; set; } = string.Empty;

    [Column("content")]
    public string Content { get; set; } = string.Empty;

    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [Column("updated_at")]
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    [Column("tags", TypeName = "text[]")]
    public List<string> Tags { get; set; } = new();

    [Column("is_archived")]
    public bool IsArchived { get; set; }

    [Column("user_id")]
    [MaxLength(128)]
    public string UserId { get; set; } = string.Empty;

    [Column("source")]
    [MaxLength(50)]
    public string Source { get; set; } = "web";

    [Column("external_id")]
    [MaxLength(256)]
    public string? ExternalId { get; set; }

    [Column("folder")]
    [MaxLength(256)]
    public string? Folder { get; set; }

    // Soft delete properties
    [Column("is_deleted")]
    public bool IsDeleted { get; set; } = false;

    [Column("deleted_at")]
    public DateTime? DeletedAt { get; set; }

    [Column("deleted_by")]
    [MaxLength(128)]
    public string? DeletedBy { get; set; }
}
