using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using NpgsqlTypes;
using Pgvector;

namespace SecondBrain.Core.Entities;

[Table("note_embeddings")]
public class NoteEmbedding
{
    [Key]
    [Column("id")]
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// UUIDv7 identifier for improved index performance (PostgreSQL 18).
    /// Generated by database default if not set.
    /// </summary>
    [Column("uuid_v7")]
    public Guid? UuidV7 { get; set; }

    [Column("note_id")]
    [MaxLength(128)]
    public string NoteId { get; set; } = string.Empty;

    [Column("user_id")]
    [MaxLength(128)]
    public string UserId { get; set; } = string.Empty;

    [Column("chunk_index")]
    public int ChunkIndex { get; set; }

    [Column("content")]
    public string Content { get; set; } = string.Empty;

    [Column("embedding", TypeName = "vector")]
    public Vector? Embedding { get; set; }

    [Column("embedding_dimensions")]
    public int EmbeddingDimensions { get; set; } = 1536;

    [Column("embedding_provider")]
    [MaxLength(50)]
    public string EmbeddingProvider { get; set; } = string.Empty;

    [Column("embedding_model")]
    [MaxLength(100)]
    public string EmbeddingModel { get; set; } = string.Empty;

    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [Column("note_updated_at")]
    public DateTime NoteUpdatedAt { get; set; } = DateTime.UtcNow;

    // Metadata for better retrieval
    [Column("note_title")]
    [MaxLength(500)]
    public string NoteTitle { get; set; } = string.Empty;

    [Column("note_tags", TypeName = "text[]")]
    public List<string> NoteTags { get; set; } = new();

    /// <summary>
    /// AI-generated summary of the note for improved RAG context.
    /// Stored with embeddings to provide semantic understanding during retrieval.
    /// </summary>
    [Column("note_summary")]
    [MaxLength(1000)]
    public string? NoteSummary { get; set; }

    // Full-text search vector for BM25/hybrid search
    [Column("search_vector")]
    public NpgsqlTsVector? SearchVector { get; set; }
}
