using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SecondBrain.Core.Entities;

/// <summary>
/// Represents a cached AI-generated progress summary for a specific date.
/// Summaries are expensive to generate, so they are cached and only regenerated
/// when tasks are completed or the user explicitly requests a refresh.
/// </summary>
[Table("progress_summaries")]
public class ProgressSummary
{
    [Key]
    [Column("id")]
    public string Id { get; set; } = string.Empty;

    [Column("user_id")]
    [MaxLength(128)]
    [Required]
    public string UserId { get; set; } = string.Empty;

    /// <summary>
    /// The date this summary is for (in user's local timezone).
    /// </summary>
    [Column("summary_date")]
    [Required]
    public DateOnly SummaryDate { get; set; }

    /// <summary>
    /// The period type: 'today' or 'week'.
    /// </summary>
    [Column("period")]
    [MaxLength(20)]
    [Required]
    public string Period { get; set; } = "today";

    // ============================================
    // Statistics (cached for quick retrieval)
    // ============================================

    /// <summary>
    /// Total number of items completed in this period.
    /// </summary>
    [Column("total_completed")]
    public int TotalCompleted { get; set; }

    /// <summary>
    /// Total minutes tracked across all completed items.
    /// </summary>
    [Column("total_minutes_tracked")]
    public int TotalMinutesTracked { get; set; }

    /// <summary>
    /// Count of P1 (high priority) items completed.
    /// </summary>
    [Column("p1_completed")]
    public int P1Completed { get; set; }

    /// <summary>
    /// Count of P2 (medium priority) items completed.
    /// </summary>
    [Column("p2_completed")]
    public int P2Completed { get; set; }

    /// <summary>
    /// Count of P3 (low priority) items completed.
    /// </summary>
    [Column("p3_completed")]
    public int P3Completed { get; set; }

    /// <summary>
    /// Consecutive days streak at the time of summary generation.
    /// </summary>
    [Column("streak_days")]
    public int StreakDays { get; set; }

    // ============================================
    // AI-Generated Content
    // ============================================

    /// <summary>
    /// AI-generated summary text describing the user's progress.
    /// </summary>
    [Column("summary")]
    [Required]
    public string Summary { get; set; } = string.Empty;

    /// <summary>
    /// AI-generated highlights as a JSON array of strings.
    /// Stored as JSONB for efficient querying.
    /// </summary>
    [Column("highlights", TypeName = "jsonb")]
    public string HighlightsJson { get; set; } = "[]";

    /// <summary>
    /// AI-generated motivational message.
    /// </summary>
    [Column("encouragement")]
    public string? Encouragement { get; set; }

    // ============================================
    // Metadata
    // ============================================

    /// <summary>
    /// AI provider used to generate this summary.
    /// </summary>
    [Column("ai_provider")]
    [MaxLength(50)]
    public string? AiProvider { get; set; }

    /// <summary>
    /// AI model used to generate this summary.
    /// </summary>
    [Column("ai_model")]
    [MaxLength(100)]
    public string? AiModel { get; set; }

    /// <summary>
    /// When this summary was generated by AI.
    /// </summary>
    [Column("generated_at")]
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Start date of the period this summary covers.
    /// </summary>
    [Column("period_start")]
    public DateOnly PeriodStart { get; set; }

    /// <summary>
    /// End date of the period this summary covers.
    /// </summary>
    [Column("period_end")]
    public DateOnly PeriodEnd { get; set; }

    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [Column("updated_at")]
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    // ============================================
    // Helper Methods
    // ============================================

    /// <summary>
    /// Gets the highlights as a list of strings.
    /// </summary>
    [NotMapped]
    public List<string> Highlights
    {
        get
        {
            if (string.IsNullOrEmpty(HighlightsJson) || HighlightsJson == "[]")
                return new List<string>();

            try
            {
                return System.Text.Json.JsonSerializer.Deserialize<List<string>>(HighlightsJson)
                    ?? new List<string>();
            }
            catch
            {
                return new List<string>();
            }
        }
        set
        {
            HighlightsJson = System.Text.Json.JsonSerializer.Serialize(value ?? new List<string>());
        }
    }

    /// <summary>
    /// Gets the completion stats as a dictionary (for API compatibility).
    /// </summary>
    [NotMapped]
    public Dictionary<int, int> CompletedByPriority => new()
    {
        { 1, P1Completed },
        { 2, P2Completed },
        { 3, P3Completed }
    };
}
