// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Pgvector;
using SecondBrain.Infrastructure.Data;

#nullable disable

namespace SecondBrain.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251205020353_AddSoftDeleteSupport")]
    partial class AddSoftDeleteSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecondBrain.Core.Entities.ChatConversation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AgentCapabilities")
                        .HasColumnType("text")
                        .HasColumnName("agent_capabilities");

                    b.Property<bool>("AgentEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("agent_enabled");

                    b.Property<bool>("AgentRagEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("agent_rag_enabled");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("ImageGenerationEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("image_generation_enabled");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<bool>("RagEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("rag_enabled");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.Property<string>("VectorStoreProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vector_store_provider");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_chat_conversations_updated_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chat_conversations_user_id");

                    b.HasIndex("UserId", "IsDeleted")
                        .HasDatabaseName("ix_conversations_user_deleted");

                    b.HasIndex("UserId", "UpdatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_conversations_user_updated");

                    b.ToTable("chat_conversations");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.ChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("conversation_id");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_ms");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("RagFeedback")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rag_feedback");

                    b.Property<string>("RagLogId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("rag_log_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_chat_messages_conversation_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_chat_messages_timestamp");

                    b.ToTable("chat_messages");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.GeneratedImageData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Base64Data")
                        .HasColumnType("text")
                        .HasColumnName("base64_data");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("media_type");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("message_id");

                    b.Property<string>("RevisedPrompt")
                        .HasColumnType("text")
                        .HasColumnName("revised_prompt");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_generated_images_message_id");

                    b.ToTable("generated_images");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.IndexingJob", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmbeddingProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("embedding_provider");

                    b.PrimitiveCollection<List<string>>("Errors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("errors");

                    b.Property<int>("ProcessedChunks")
                        .HasColumnType("integer")
                        .HasColumnName("processed_chunks");

                    b.Property<int>("ProcessedNotes")
                        .HasColumnType("integer")
                        .HasColumnName("processed_notes");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("integer")
                        .HasColumnName("total_chunks");

                    b.Property<int>("TotalNotes")
                        .HasColumnType("integer")
                        .HasColumnName("total_notes");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_indexing_jobs_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_indexing_jobs_user_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_indexing_jobs_user_created");

                    b.ToTable("indexing_jobs");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.MessageImage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Base64Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base64_data");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("media_type");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("message_id");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_message_images_message_id");

                    b.ToTable("message_images");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.Note", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<string>("Folder")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("folder");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_notes_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notes_user_id");

                    b.HasIndex("UserId", "ExternalId")
                        .HasDatabaseName("ix_notes_user_external");

                    b.HasIndex("UserId", "Folder")
                        .HasDatabaseName("ix_notes_user_folder")
                        .HasFilter("folder IS NOT NULL");

                    b.HasIndex("UserId", "IsArchived")
                        .HasDatabaseName("ix_notes_user_archived");

                    b.HasIndex("UserId", "IsDeleted")
                        .HasDatabaseName("ix_notes_user_deleted");

                    b.HasIndex("UserId", "UpdatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_notes_user_updated");

                    b.ToTable("notes");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.NoteEmbedding", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("embedding_model");

                    b.Property<string>("EmbeddingProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("embedding_provider");

                    b.Property<string>("NoteId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("note_id");

                    b.PrimitiveCollection<List<string>>("NoteTags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("note_tags");

                    b.Property<string>("NoteTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note_title");

                    b.Property<DateTime>("NoteUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("note_updated_at");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("NoteId")
                        .HasDatabaseName("ix_note_embeddings_note_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_note_embeddings_user_id");

                    b.HasIndex("NoteId", "ChunkIndex")
                        .HasDatabaseName("ix_note_embeddings_note_chunk");

                    b.HasIndex("UserId", "NoteId")
                        .HasDatabaseName("ix_embeddings_user_note");

                    b.ToTable("note_embeddings");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.RagQueryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float?>("AvgBM25Score")
                        .HasColumnType("real")
                        .HasColumnName("avg_bm25_score");

                    b.Property<float?>("AvgCosineScore")
                        .HasColumnType("real")
                        .HasColumnName("avg_cosine_score");

                    b.Property<float?>("AvgRerankScore")
                        .HasColumnType("real")
                        .HasColumnName("avg_rerank_score");

                    b.Property<int?>("BM25SearchTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("bm25_search_time_ms");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FeedbackCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("feedback_category");

                    b.Property<string>("FeedbackComment")
                        .HasColumnType("text")
                        .HasColumnName("feedback_comment");

                    b.Property<int?>("FinalCount")
                        .HasColumnType("integer")
                        .HasColumnName("final_count");

                    b.Property<bool>("HyDEEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("hyde_enabled");

                    b.Property<bool>("HybridSearchEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("hybrid_search_enabled");

                    b.Property<bool>("MultiQueryEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("multi_query_enabled");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query");

                    b.Property<string>("QueryEmbeddingJson")
                        .HasColumnType("text")
                        .HasColumnName("query_embedding");

                    b.Property<int?>("QueryEmbeddingTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("query_embedding_time_ms");

                    b.Property<int?>("RerankTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("rerank_time_ms");

                    b.Property<bool>("RerankingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("reranking_enabled");

                    b.Property<int?>("RetrievedCount")
                        .HasColumnType("integer")
                        .HasColumnName("retrieved_count");

                    b.Property<float?>("TopCosineScore")
                        .HasColumnType("real")
                        .HasColumnName("top_cosine_score");

                    b.Property<float?>("TopRerankScore")
                        .HasColumnType("real")
                        .HasColumnName("top_rerank_score");

                    b.Property<int?>("TopicCluster")
                        .HasColumnType("integer")
                        .HasColumnName("topic_cluster");

                    b.Property<string>("TopicLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("topic_label");

                    b.Property<int?>("TotalTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("total_time_ms");

                    b.Property<string>("UserFeedback")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("user_feedback");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.Property<int?>("VectorSearchTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("vector_search_time_ms");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_rag_query_logs_conversation");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_rag_query_logs_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_rag_query_logs_user_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_rag_logs_user_created");

                    b.ToTable("rag_query_logs");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.RetrievedNote", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ChunkContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chunk_content");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("message_id");

                    b.Property<string>("NoteId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("note_id");

                    b.Property<float>("RelevanceScore")
                        .HasColumnType("real")
                        .HasColumnName("relevance_score");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_retrieved_notes_message_id");

                    b.ToTable("retrieved_notes");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.ToolCall", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arguments");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("message_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tool_name");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_tool_calls_message_id");

                    b.ToTable("tool_calls");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("api_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .HasDatabaseName("ix_users_api_key");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.UserPreferences", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ChatModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chat_model");

                    b.Property<string>("ChatProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("chat_provider");

                    b.Property<string>("DefaultNoteView")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("default_note_view");

                    b.Property<bool>("EnableNotifications")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_notifications");

                    b.Property<string>("FontSize")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("font_size");

                    b.Property<int>("ItemsPerPage")
                        .HasColumnType("integer")
                        .HasColumnName("items_per_page");

                    b.Property<string>("OllamaRemoteUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ollama_remote_url");

                    b.Property<bool>("UseRemoteOllama")
                        .HasColumnType("boolean")
                        .HasColumnName("use_remote_ollama");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.Property<string>("VectorStoreProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vector_store_provider");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_preferences_user_id");

                    b.ToTable("user_preferences");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.ChatMessage", b =>
                {
                    b.HasOne("SecondBrain.Core.Entities.ChatConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.GeneratedImageData", b =>
                {
                    b.HasOne("SecondBrain.Core.Entities.ChatMessage", "Message")
                        .WithMany("GeneratedImages")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.MessageImage", b =>
                {
                    b.HasOne("SecondBrain.Core.Entities.ChatMessage", "Message")
                        .WithMany("Images")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.RetrievedNote", b =>
                {
                    b.HasOne("SecondBrain.Core.Entities.ChatMessage", "Message")
                        .WithMany("RetrievedNotes")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.ToolCall", b =>
                {
                    b.HasOne("SecondBrain.Core.Entities.ChatMessage", "Message")
                        .WithMany("ToolCalls")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.UserPreferences", b =>
                {
                    b.HasOne("SecondBrain.Core.Entities.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("SecondBrain.Core.Entities.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.ChatConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.ChatMessage", b =>
                {
                    b.Navigation("GeneratedImages");

                    b.Navigation("Images");

                    b.Navigation("RetrievedNotes");

                    b.Navigation("ToolCalls");
                });

            modelBuilder.Entity("SecondBrain.Core.Entities.User", b =>
                {
                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
