-- Migration: Add topic clustering columns to rag_query_logs table
-- This migration adds support for topic clustering analysis

-- Add topic clustering columns
ALTER TABLE rag_query_logs
ADD COLUMN IF NOT EXISTS topic_cluster INTEGER,
ADD COLUMN IF NOT EXISTS topic_label VARCHAR(100),
ADD COLUMN IF NOT EXISTS query_embedding TEXT;

-- Create index for topic clustering queries
CREATE INDEX IF NOT EXISTS idx_rag_query_logs_topic_cluster 
ON rag_query_logs(topic_cluster) 
WHERE topic_cluster IS NOT NULL;

-- Add comment for documentation
COMMENT ON COLUMN rag_query_logs.topic_cluster IS 'Cluster ID assigned by K-means clustering algorithm';
COMMENT ON COLUMN rag_query_logs.topic_label IS 'Human-readable label for the topic cluster, generated by LLM';
COMMENT ON COLUMN rag_query_logs.query_embedding IS 'JSON array of embedding values for the query, used for clustering';

