import { AIModel } from '../../types/ai';

export const ANTHROPIC_MODELS: AIModel[] = [
    {
        id: 'claude-3-5-sonnet-20241022',
        name: 'Claude 3.5 Sonnet (latest)',
        provider: 'anthropic',
        category: 'chat',
        description: 'Most intelligent model with high capability and fast response times',
        isConfigured: true,
        isReasoner: false,
        color: '#F97316',
        endpoint: 'chat',
        rateLimits: {
            maxInputTokens: 200000,
            maxOutputTokens: 8192,
            tpm: 100000,
            rpm: 50,
        },
        size: '175B',
    },
    {
        id: 'claude-3-5-haiku-20241022',
        name: 'Claude 3.5 Haiku (latest)',
        provider: 'anthropic',
        category: 'chat',
        description: 'Fastest model with high intelligence and quick response times',
        isConfigured: true,
        isReasoner: false,
        color: '#F97316',
        endpoint: 'chat',
        rateLimits: {
            maxInputTokens: 200000,
            maxOutputTokens: 8192,
            tpm: 100000,
            rpm: 50,
        },
        size: '175B',
    },
    {
        id: 'claude-3-opus-20240229',
        name: 'Claude 3 Opus (latest)',
        provider: 'anthropic',
        category: 'chat',
        description: 'Most powerful model for highly complex tasks with top-level intelligence and understanding',
        isConfigured: true,
        isReasoner: false,
        color: '#F97316',
        endpoint: 'chat',
        rateLimits: {
            maxInputTokens: 200000,
            maxOutputTokens: 4096,
            tpm: 100000,
            rpm: 50,
        },
        size: '175B',
    },
    {
        id: 'claude-3-sonnet-20240229',
        name: 'Claude 3 Sonnet',
        provider: 'anthropic',
        category: 'chat',
        description: 'Balanced model optimized for production deployments with strong utility',
        isConfigured: true,
        isReasoner: false,
        color: '#F97316',
        endpoint: 'chat',
        rateLimits: {
            maxInputTokens: 200000,
            maxOutputTokens: 4096,
            tpm: 100000,
            rpm: 50,
        },
        size: '175B',
    },
    {
        id: 'claude-3-haiku-20240307',
        name: 'Claude 3 Haiku',
        provider: 'anthropic',
        category: 'chat',
        description: 'Fastest and most compact model for near-instant responsiveness',
        isConfigured: true,
        isReasoner: false,
        color: '#F97316',
        endpoint: 'chat',
        rateLimits: {
            maxInputTokens: 200000,
            maxOutputTokens: 4096,
            tpm: 100000,
            rpm: 50,
        },
        size: '175B',
    },
    {
        id: 'claude-3-7-sonnet-20250219',
        name: 'Claude 3.7 Sonnet',
        provider: 'anthropic',
        category: 'chat',
        description: 'Most advanced Claude model with hybrid reasoning and extended thinking capabilities',
        isConfigured: true,
        isReasoner: true,
        color: '#F97316',
        endpoint: 'chat',
        rateLimits: {
            maxInputTokens: 200000,
            maxOutputTokens: 8192,
            tpm: 100000,
            rpm: 50,
        },
        size: '175B',
    },
    {
        id: 'claude-3-7-sonnet-20250219',
        name: 'Claude 3.7 Sonnet (Agent)',
        provider: 'anthropic',
        category: 'agent',
        description: 'Advanced Claude research agent with extended thinking and step-by-step reasoning',
        isConfigured: true,
        isReasoner: true,
        color: '#F97316',
        endpoint: 'agent',
        rateLimits: {
            maxInputTokens: 200000,
            maxOutputTokens: 8192,
            tpm: 100000,
            rpm: 50,
        },
        size: '175B',
    },
    {
        id: 'claude-3-5-sonnet-20241022',
        name: 'Claude 3 Sonnet (Agent)',
        provider: 'anthropic',
        category: 'agent',
        description: 'Balanced Claude model for agent tasks with strong performance',
        isConfigured: true,
        isReasoner: true,
        color: '#F97316',
        endpoint: 'agent',
        rateLimits: {
            maxInputTokens: 200000,
            maxOutputTokens: 4096,
            tpm: 100000,
            rpm: 50,
        },
        size: '175B',
    },
    {
        id: 'claude-3-5-haiku-20241022',
        name: 'Claude 3 Haiku (Agent)',
        provider: 'anthropic',
        category: 'agent',
        description: 'Fast Claude model for quick agent responses',
        isConfigured: true,
        isReasoner: true,
        color: '#F97316',
        endpoint: 'agent',
        rateLimits: {
            maxInputTokens: 200000,
            maxOutputTokens: 4096,
            tpm: 100000,
            rpm: 50,
        },
        size: '175B',
    },
]; 