import { AIModel } from '../../types/ai';

export const GEMINI_MODELS: AIModel[] = [
    {
        id: 'gemini-1.5-pro',
        name: 'Gemini 1.5 Pro',
        provider: 'gemini',
        category: 'chat',
        description: 'Google Gemini 1.5 Pro model optimized for agent tasks.',
        isConfigured: true,
        isReasoner: false,
        color: '#4285F4',
        endpoint: 'chat',
        rateLimits: {
            tpm: 100000,
            rpm: 60,
        },
        size: '1.5T',
    },
    {
        id: 'gemini-2.0-flash-exp',
        name: 'Gemini 2.0 Flash Exp',
        provider: 'gemini',
        category: 'chat',
        description: 'Google Gemini 2.0 Flash Exp model optimized for agent tasks.',
        isConfigured: true,
        isReasoner: false,
        color: '#4285F4',
        endpoint: 'chat',
        rateLimits: {
            tpm: 100000,
            rpm: 60,
        },
        size: '2T',
    },
    {
        id: 'gemini-1.5-flash',
        name: 'Gemini 1.5 Flash',
        provider: 'gemini',
        category: 'chat',
        description: 'Google Gemini 1.5 Flash model optimized for agent tasks.',
        isConfigured: true,
        isReasoner: false,
        color: '#4285F4',
        endpoint: 'chat',
        rateLimits: {
            tpm: 100000,
            rpm: 60,
        },
        size: '1.5T',
    },
    {
        id: 'gemini-1.5-flash-8b',
        name: 'Gemini 1.5 Flash-8B',
        provider: 'gemini',
        category: 'chat',
        description: 'Google Gemini 1.5 Flash-8B model optimized for agent tasks.',
        isConfigured: true,
        isReasoner: false,
        color: '#4285F4',
        endpoint: 'chat',
        rateLimits: {
            tpm: 100000,
            rpm: 60,
        },
        size: '8B',
    },
    {
        id: 'gemini-1.0-pro',
        name: 'Gemini 1.0 Pro',
        provider: 'gemini',
        category: 'chat',
        description: 'Google Gemini 1.0 Pro model optimized for agent tasks.',
        isConfigured: true,
        isReasoner: false,
        color: '#4285F4',
        endpoint: 'chat',
        rateLimits: {
            tpm: 60000,
            rpm: 45,
        },
    },
    {
        id: 'gemini-2.0-flash-exp',
        name: 'Gemini 2.0 Flash Exp',
        provider: 'gemini',
        category: 'agent',
        description: 'Google Gemini 2.0 Flash Exp model optimized for agent tasks.',
        isConfigured: true,
        isReasoner: false,
        color: '#4285F4',
        endpoint: 'agent',
        rateLimits: {
            tpm: 100000,
            rpm: 60,
        },
        size: '2T',
    },
    {
        id: 'gemini-1.5-pro-agent',
        name: 'Gemini 1.5 Pro (Agent)',
        provider: 'gemini',
        category: 'agent',
        description: 'Google Gemini 1.5 Pro model optimized for agent tasks.',
        isConfigured: true,
        isReasoner: false,
        color: '#4285F4',
        endpoint: 'agent',
        rateLimits: {
            tpm: 100000,
            rpm: 60,
        },
        size: '1.5T',
    },
    {
        id: 'gemini-1.5-flash-agent',
        name: 'Gemini 1.5 Flash (Agent)',
        provider: 'gemini',
        category: 'agent',
        description: 'Google Gemini 1.5 Flash model optimized for agent tasks.',
        isConfigured: true,
        isReasoner: false,
        color: '#4285F4',
        endpoint: 'agent',
        rateLimits: {
            tpm: 100000,
            rpm: 60,
        },
        size: '1.5T',
    },
    {
        id: 'gemini-1.5-flash-8b-agent',
        name: 'Gemini 1.5 Flash-8B (Agent)',
        provider: 'gemini',
        category: 'agent',
        description: 'Google Gemini 1.5 Flash-8B model optimized for agent tasks.',
        isConfigured: true,
        isReasoner: false,
        color: '#4285F4',
        endpoint: 'agent',
        rateLimits: {
            tpm: 100000,
            rpm: 60,
        },
        size: '8B',
    },
    {
        id: 'gemini-1.0-pro-agent',
        name: 'Gemini 1.0 Pro (Agent)',
        provider: 'gemini',
        category: 'agent',
        description: 'Google Gemini 1.0 Pro model optimized for agent tasks.',
        isConfigured: true,
        isReasoner: false,
        color: '#4285F4',
        endpoint: 'agent',
        rateLimits: {
            tpm: 60000,
            rpm: 45,
        },
    },
    {
        id: 'gemini-2.5-flash-preview-04-17',
        name: 'Gemini 2.5 Flash Preview 04-17',
        provider: 'gemini',
        category: 'chat',
        description: 'Adaptive thinking and cost efficiency. Supports audio, image, video, and text inputs; text outputs.',
        isConfigured: true,
        isReasoner: true,
        color: '#4285F4',
        endpoint: 'chat',
        rateLimits: { tpm: 100000, rpm: 60 },
    },
    {
        id: 'gemini-2.5-pro-preview-05-06',
        name: 'Gemini 2.5 Pro Preview',
        provider: 'gemini',
        category: 'chat',
        description: 'Enhanced thinking and reasoning, multimodal understanding, advanced coding. Supports audio, image, video, and text inputs; text outputs.',
        isConfigured: true,
        isReasoner: true,
        color: '#4285F4',
        endpoint: 'chat',
        rateLimits: { tpm: 100000, rpm: 60 },
    },
    {
        id: 'gemini-2.0-flash',
        name: 'Gemini 2.0 Flash',
        provider: 'gemini',
        category: 'chat',
        description: 'Next-gen speed, thinking, streaming, and multimodal generation. Supports audio, image, video, and text inputs; text, experimental image, and upcoming audio outputs.',
        isConfigured: true,
        isReasoner: false,
        color: '#4285F4',
        endpoint: 'chat',
        rateLimits: { tpm: 100000, rpm: 60 },
        size: '2T',
    },
    {
        id: 'gemini-2.0-flash-lite',
        name: 'Gemini 2.0 Flash-Lite',
        provider: 'gemini',
        category: 'chat',
        description: 'Cost efficiency and low latency. Supports audio, image, video, and text inputs; text outputs.',
        isConfigured: true,
        isReasoner: false,
        color: '#4285F4',
        endpoint: 'chat',
        rateLimits: { tpm: 100000, rpm: 60 },
    },
    {
        id: 'gemini-embedding-exp',
        name: 'Gemini Embedding Exp',
        provider: 'gemini',
        category: 'embedding',
        description: 'Generates text embeddings from text inputs for measuring string relatedness.',
        isConfigured: true,
        isReasoner: false,
        color: '#4285F4',
        endpoint: 'embeddings',
    },
    {
        id: 'imagen-3.0-generate-002',
        name: 'Imagen 3',
        provider: 'gemini',
        category: 'image',
        description: 'Advanced image generation from text inputs.',
        isConfigured: true,
        isReasoner: false,
        color: '#4285F4',
        endpoint: 'images',
    },
    {
        id: 'veo-2.0-generate-001',
        name: 'Veo 2',
        provider: 'gemini',
        category: 'agent',
        description: 'High-quality video generation from text and image inputs.',
        isConfigured: true,
        isReasoner: false,
        color: '#4285F4',
        endpoint: 'agent',
    },
    {
        id: 'gemini-2.0-flash-live-001',
        name: 'Gemini 2.0 Flash Live',
        provider: 'gemini',
        category: 'chat',
        description: 'Live version of Gemini 2.0 Flash for real-time interactions. Supports multimodal inputs and text outputs.',
        isConfigured: true,
        isReasoner: false,
        color: '#4285F4',
        endpoint: 'chat',
        rateLimits: { tpm: 100000, rpm: 60 },
    }
]; 