import { AIModel } from '../../types/ai';

export const GEMINI_MODELS: AIModel[] = [
    {
        id: 'gemini-1.5-pro',
        name: 'Gemini 1.5 Pro',
        provider: 'gemini',
        category: 'chat',
        description: 'Google Gemini 1.5 Pro model optimized for agent tasks.',
        isConfigured: true,
        isReasoner: true,
        color: '#4285F4',
        endpoint: 'chat',
        rateLimits: {
            tpm: 100000,
            rpm: 60,
        },
        size: '1.5T',
    },
    {
        id: 'gemini-2.0-flash-exp',
        name: 'Gemini 2.0 Flash Exp',
        provider: 'gemini',
        category: 'chat',
        description: 'Google Gemini 2.0 Flash Exp model optimized for agent tasks.',
        isConfigured: true,
        isReasoner: true,
        color: '#4285F4',
        endpoint: 'chat',
        rateLimits: {
            tpm: 100000,
            rpm: 60,
        },
        size: '2T',
    },
    {
        id: 'gemini-1.5-flash',
        name: 'Gemini 1.5 Flash',
        provider: 'gemini',
        category: 'chat',
        description: 'Google Gemini 1.5 Flash model optimized for agent tasks.',
        isConfigured: true,
        isReasoner: true,
        color: '#4285F4',
        endpoint: 'chat',
        rateLimits: {
            tpm: 100000,
            rpm: 60,
        },
        size: '1.5T',
    },
    {
        id: 'gemini-1.5-flash-8b',
        name: 'Gemini 1.5 Flash-8B',
        provider: 'gemini',
        category: 'chat',
        description: 'Google Gemini 1.5 Flash-8B model optimized for agent tasks.',
        isConfigured: true,
        isReasoner: true,
        color: '#4285F4',
        endpoint: 'chat',
        rateLimits: {
            tpm: 100000,
            rpm: 60,
        },
        size: '8B',
    },
    {
        id: 'gemini-1.0-pro',
        name: 'Gemini 1.0 Pro',
        provider: 'gemini',
        category: 'chat',
        description: 'Google Gemini 1.0 Pro model optimized for agent tasks.',
        isConfigured: true,
        isReasoner: true,
        color: '#4285F4',
        endpoint: 'chat',
        rateLimits: {
            tpm: 60000,
            rpm: 45,
        },
    },
    {
        id: 'gemini-2.0-flash-exp',
        name: 'Gemini 2.0 Flash Exp',
        provider: 'gemini',
        category: 'agent',
        description: 'Google Gemini 2.0 Flash Exp model optimized for agent tasks.',
        isConfigured: true,
        isReasoner: true,
        color: '#4285F4',
        endpoint: 'agent',
        rateLimits: {
            tpm: 100000,
            rpm: 60,
        },
        size: '2T',
    },
    {
        id: 'gemini-1.5-pro-agent',
        name: 'Gemini 1.5 Pro (Agent)',
        provider: 'gemini',
        category: 'agent',
        description: 'Google Gemini 1.5 Pro model optimized for agent tasks.',
        isConfigured: true,
        isReasoner: true,
        color: '#4285F4',
        endpoint: 'agent',
        rateLimits: {
            tpm: 100000,
            rpm: 60,
        },
        size: '1.5T',
    },
    {
        id: 'gemini-1.5-flash-agent',
        name: 'Gemini 1.5 Flash (Agent)',
        provider: 'gemini',
        category: 'agent',
        description: 'Google Gemini 1.5 Flash model optimized for agent tasks.',
        isConfigured: true,
        isReasoner: true,
        color: '#4285F4',
        endpoint: 'agent',
        rateLimits: {
            tpm: 100000,
            rpm: 60,
        },
        size: '1.5T',
    },
    {
        id: 'gemini-1.5-flash-8b-agent',
        name: 'Gemini 1.5 Flash-8B (Agent)',
        provider: 'gemini',
        category: 'agent',
        description: 'Google Gemini 1.5 Flash-8B model optimized for agent tasks.',
        isConfigured: true,
        isReasoner: true,
        color: '#4285F4',
        endpoint: 'agent',
        rateLimits: {
            tpm: 100000,
            rpm: 60,
        },
        size: '8B',
    },
    {
        id: 'gemini-1.0-pro-agent',
        name: 'Gemini 1.0 Pro (Agent)',
        provider: 'gemini',
        category: 'agent',
        description: 'Google Gemini 1.0 Pro model optimized for agent tasks.',
        isConfigured: true,
        isReasoner: true,
        color: '#4285F4',
        endpoint: 'agent',
        rateLimits: {
            tpm: 60000,
            rpm: 45,
        },
    }
]; 