import { AIModel } from '../../types/ai';

export const OPENAI_MODELS: AIModel[] = [
    {
        id: 'o1-preview',
        name: 'O1 Preview',
        provider: 'openai',
        category: 'chat',
        description: 'Most capable reasoning model',
        isConfigured: true,
        isReasoner: false,
        color: '#3B7443',
        endpoint: 'chat',
        rateLimits: {
            tpm: 8000,
            rpm: 500,
            maxOutputTokens: 8192,
            maxInputTokens: 10000,
        },
        size: '1.76T',
    },
    {
        id: 'gpt-4-turbo',
        name: 'GPT-4 Turbo',
        provider: 'openai',
        category: 'chat',
        description: 'Enhanced GPT-4 with higher rate limits',
        isConfigured: true,
        isReasoner: false,
        color: '#3B7443',
        endpoint: 'chat',
        rateLimits: {
            tpm: 30000,
            rpm: 500,
            tpd: 90000,
        },
        size: '1.76T',
    },
    {
        id: 'gpt-4o',
        name: 'GPT-4 Optimized',
        provider: 'openai',
        category: 'chat',
        description: 'Optimized version of GPT-4',
        isConfigured: true,
        isReasoner: false,
        color: '#3B7443',
        endpoint: 'chat',
        rateLimits: {
            tpm: 30000,
            rpm: 500,
            tpd: 90000,
        },
        size: '1.76T',
    },
    {
        id: 'gpt-4o-mini',
        name: 'GPT-4 Optimized Mini',
        provider: 'openai',
        category: 'chat',
        description: 'Lightweight GPT-4 with higher token limits',
        isConfigured: true,
        isReasoner: false,
        color: '#3B7443',
        endpoint: 'chat',
        rateLimits: {
            tpm: 200000,
            rpm: 500,
            rpd: 10000,
            tpd: 2000000,
        },
        size: '1.76T',
    },
    {
        id: 'gpt-3.5-turbo',
        name: 'GPT-3.5 Turbo',
        provider: 'openai',
        category: 'chat',
        description: 'Fast and cost-effective chat model',
        isConfigured: true,
        isReasoner: false,
        color: '#3B7443',
        endpoint: 'chat',
        rateLimits: {
            tpm: 200000,
            rpm: 500,
            rpd: 10000,
            tpd: 2000000,
        },
        size: '175B',
    },
    {
        id: 'text-embedding-3-small',
        name: 'Text Embedding 3 Small',
        provider: 'openai',
        category: 'embedding',
        description: 'Efficient text embedding generation',
        isConfigured: true,
        isReasoner: false,
        color: '#3B7443',
        endpoint: 'embeddings',
        rateLimits: {
            tpm: 1000000,
            rpm: 3000,
            tpd: 3000000,
        },
        size: '1.5B',
    },
    {
        id: 'dall-e-3',
        name: 'DALL·E 3',
        provider: 'openai',
        category: 'image',
        description: 'Advanced image generation',
        isConfigured: true,
        isReasoner: false,
        color: '#3B7443',
        endpoint: 'images',
        rateLimits: {
            rpm: 500,
            imagesPerMinute: 5,
        },
        size: '20B',
    },
    {
        id: 'whisper-1',
        name: 'Whisper v1',
        provider: 'openai',
        category: 'audio',
        description: 'Speech to text transcription',
        isConfigured: true,
        isReasoner: false,
        color: '#3B7443',
        endpoint: 'audio',
        rateLimits: {
            rpm: 500,
        },
        size: '1.5B',
    },
    {
        id: 'tts-1',
        name: 'TTS-1',
        provider: 'openai',
        category: 'audio',
        description: 'Text to speech conversion',
        isConfigured: true,
        isReasoner: false,
        color: '#3B7443',
        endpoint: 'audio',
        rateLimits: {
            rpm: 500,
        },
        size: '1B',
    },
    {
        id: 'gpt-4-turbo',
        name: 'GPT-4 Turbo (Agent)',
        provider: 'openai',
        category: 'agent',
        description: 'Enhanced GPT-4 with higher rate limits',
        isConfigured: true,
        isReasoner: false,
        color: '#3B7443',
        endpoint: 'agent',
        rateLimits: {
            tpm: 30000,
            rpm: 500,
            tpd: 90000,
        },
        size: '1.76T',
    },
    {
        id: 'gpt-4o',
        name: 'GPT-4 Optimized (Agent)',
        provider: 'openai',
        category: 'agent',
        description: 'Optimized version of GPT-4',
        isConfigured: true,
        isReasoner: false,
        color: '#3B7443',
        endpoint: 'agent',
        rateLimits: {
            tpm: 30000,
            rpm: 500,
            tpd: 90000,
        },
        size: '1.76T',
    },
    {
        id: 'gpt-4o-mini',
        name: 'GPT-4 Optimized Mini (Agent)',
        provider: 'openai',
        category: 'agent',
        description: 'Lightweight GPT-4 with higher token limits',
        isConfigured: true,
        isReasoner: false,
        color: '#3B7443',
        endpoint: 'agent',
        rateLimits: {
            tpm: 200000,
            rpm: 500,
            rpd: 10000,
            tpd: 2000000,
        },
        size: '1.76T',
    },
]; 